### ISSUE TITLE
Documentation for Choices

### ISSUE THREAD

**Issue by khionu** [baptiste0928/twilight-interactions#33]
I noticed that there doesn't appear to be any documentation for how choices can be defined? Would be great if that could be added

**Comment by khionu** [comment]
I just noticed that you do have them, but you call choices "options". It would be a breaking change, but I would suggest renaming the trait.

**Comment by baptiste0928** [comment]
Hello, thanks for your feedback. The traits are called `CommandOption`/`CreateOption` because they are being used to parse and create [command option](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure), not just those with choices. Choices are also not a separate type on the Discord API either, it's an option field of a command option.

There is [an implementation](https://docs.rs/twilight-interactions/latest/twilight_interactions/command/trait.CommandOption.html#foreign-impls) of this trait for every type that this library can parse from a command option, so it's not limited to the implementations generated by the choices derive macro.

So I think it's more a problem with the overall documentation of the crate that makes this feature hard to discover than with the name, the trait is correctly named based on what it does.

**Comment by baptiste0928** [comment]
I added a mention of command choices in the "supported types" section of the module documentation, linking to the CommandOption/CreateOption traits. I will close the issue for now and will consider a larger refactoring of the documentation if I receive more feedback about similar features being hard to discover.
